name: build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: update gcc and libstdc++
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-13 g++-13 libstdc++-13-dev

      - name: build
        run: |
          export CXX=g++-13
          ./mkheat.sh 64 131072
          make -j4

