name: build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-25.10

    steps:
      - uses: actions/checkout@v4

      - name: update gcc-14 and libstdc++14
        run: |
          sudo apt update
          sudo apt install -y gcc-15 g++-15

      - name: build
        run: |
          export CXX=g++-15
          ./mkheat.sh 64 131072
          make -j4

